services:
  reverse_proxy:
    build:
      context: ../../docker
      dockerfile: Dockerfile-nginx

    restart: always
    ports:
      - 8080:80
      - 8443:443

    volumes:          
      - type: bind
        source: ../../docker/nginx/server.conf
        target: /etc/nginx/nginx.conf
        read_only: true

      - type: bind
        source: ../../docker/nginx/lumen
        target: /conf/
        read_only: true

      - type: bind
        source: $HOME/certbot
        target: /etc/nginx/ssl/
        read_only: true
