Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  
  cpus = 2
  memory = 2048
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = memory
    vb.cpus = cpus
  end
  
  config.vm.network "private_network", ip: "10.0.0.10"
end
