Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Configuration de la VM1
  config.vm.define "lb" do |lb|
    lb.vm.network "private_network", ip: "10.0.0.10"
    lb.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    lb.vm.provision "shell", path: "script_lb.sh"
  end

  # Configuration de la VM2
  config.vm.define "web1" do |web1|
    web1.vm.network "private_network", ip: "10.0.0.11"
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    web1.vm.provision "shell", path: "script_web1.sh"
  end

  # Configuration de la VM3
  config.vm.define "web2" do |web2|
    web2.vm.network "private_network", ip: "10.0.0.12"
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    web2.vm.provision "shell", path: "script_web2.sh"
  end
end
